### ISSUE TITLE
Armor Slots

### ISSUE THREAD

**Issue by ghost** [KalmeMarq/Minecraft-JS#2]
Maybe add a prop named 'is_armor' or something like that because currently, you can put anything in the armor slots.

**Comment by ghost** [comment]
Actually itd be better for a prop named 'armor' but itd be a object cause youd be able to put pants in helmet slot if not
`
{
    armor: { type: 'helmet' }
 }`

**Comment by KalmeMarq** [comment]
I'm still wondering about the items props. I'm thinking about doing the same they do on java. instead of new Item() be new Registry() and then the Register constructor have the id, name, texture and props. In the pros I could do new ArmorItem() or new FoodItem() and then assign their own keys/values.

class ArmorItem extends Item() {
  constructor(slot, gear, ....) { .... }
}

new Registry('diamond_helmet',  new ArmorItem(39, 'diamond'));

**Comment by ghost** [comment]
Ah yes! I remember something similar when I use to make mods.
